# Generated by Django 3.2 on 2021-05-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='numero',
            field=models.IntegerField(help_text="Vous pouvez numéroter le chapitre pour permettre         un classement dans l'ordre du programme (facultatif)", null=True),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='matiere',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Chimie', 'Chimie'), ('Physique', 'Physique')], max_length=40),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
