# Generated by Django 3.2.2 on 2021-05-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0002_auto_20210517_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='correction',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
    ]
