# Generated by Django 3.2 on 2021-05-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0003_auto_20210514_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='numero',
            field=models.IntegerField(default=1, help_text="Vous pouvez numéroter le chapitre/module         pour permettre un classement dans l'ordre du programme (recommandé,         la valeur par défaut est 1)", null=True),
        ),
    ]
