# Generated by Django 3.2 on 2021-05-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0003_fichier_correction'),
        ('exo', '0004_alter_chapitre_numero'),
    ]

    operations = [
    ]
