# Generated by Django 3.2 on 2021-05-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0004_alter_chapitre_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisation',
            name='date',
        ),
        migrations.AddField(
            model_name='utilisation',
            name='fichier',
            field=models.ManyToManyField(blank=True, to='exo.Fichier'),
        ),
    ]
