# Generated by Django 3.2 on 2021-05-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0005_auto_20210514_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='format',
            field=models.CharField(choices=[('w', 'Document Word'), ('p', 'PDF'), ('t', 'LaTeX'), ('i', 'Image')], max_length=2),
        ),
    ]
