# Generated by Django 3.2 on 2021-05-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0005_merge_20210519_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='difficulte',
            field=models.IntegerField(choices=[('1', '*'), ('2', '**'), ('3', '***')], null=True),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='format',
            field=models.CharField(choices=[('w', 'Document Word'), ('p', 'PDF'), ('t', 'LaTeX'), ('i', 'Image')], max_length=2),
        ),
    ]
