# Generated by Django 3.2 on 2021-05-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0006_auto_20210519_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='difficulte',
            field=models.IntegerField(choices=[('*', '*'), ('**', '**'), ('***', '***')], null=True),
        ),
    ]
