# Generated by Django 3.2 on 2021-05-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0003_fichier_correction'),
        ('exo', '0006_alter_fichier_format'),
    ]

    operations = [
    ]
