# Generated by Django 3.2 on 2021-05-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0007_alter_exercice_difficulte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='difficulte',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')], null=True),
        ),
    ]
