# Generated by Django 3.2.2 on 2021-05-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0009_alter_exercice_difficulte'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='provenance',
            field=models.CharField(default='', max_length=200),
        ),
    ]
