# Generated by Django 3.2 on 2021-05-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0010_exercice_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='numero',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='numero',
            field=models.IntegerField(default=1, error_messages={'invalid_choice': 'Ce numéro de chapitre existe déjà.'}, help_text="Vous pouvez numéroter le chapitre/module         pour permettre un classement dans l'ordre du programme (recommandé,         la valeur par défaut est 1)", null=True, unique=True),
        ),
    ]
