# Generated by Django 3.2 on 2021-05-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0012_remove_exercice_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
