# Generated by Django 3.2 on 2021-06-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0013_exercice_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='difficulte',
            field=models.IntegerField(blank=True, choices=[(1, '*'), (2, '**'), (3, '***')], null=True),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='provenance',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
