# Generated by Django 3.2 on 2021-06-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0014_auto_20210601_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
