# Generated by Django 3.2 on 2021-06-01 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0016_auto_20210601_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='date_modif',
        ),
        migrations.AddField(
            model_name='fichier',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fichier',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
