# Generated by Django 3.2 on 2021-06-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0017_auto_20210601_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='fichier',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='numero',
            field=models.IntegerField(default=1, help_text="Numérotez le chapitre/module         pour permettre un classement dans l'ordre du programme (recommandé,         la valeur par défaut est 1)", null=True),
        ),
    ]
