# Generated by Django 3.2.2 on 2021-06-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0018_auto_20210602_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisation',
            name='fichier',
        ),
    ]
